name: Build Gem

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@93287a1fa82c6ddbb6d8db978df4b0119cd8879f
        with:
          bundler-cache: true

      - run: gem build test.gemspec
        name:  Build gem
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ secrets.REGISTRY_USER }}/actions-playground:latest
          platforms: linux/amd64,linux/arm64
