name: Output Test

on:
  push:
    branches: [main]

jobs:
  output-testing:
    runs-on: ubuntu-latest
    steps:
      - run: |-
          echo "fooSecret=$(curl 'http://www.randomnumberapi.com/api/v1.0/random')" >> $GITHUB_OUTPUT
          echo "barSecret=$(curl 'http://www.randomnumberapi.com/api/v1.0/random')" >> $GITHUB_OUTPUT
        id: step1
      - run: |-
          echo ${{ steps.step1.outputs.fooSecret }}
          echo ${{ steps.step1.outputs.barSecret }}
  az-cli-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - id: az-cli-testing
        run: |-
          echo secret1=$(az keyvault secret show --vault-name chaseTestVault --name secret1 --query value) >> $GITHUB_ENV
          echo secret2=$(az keyvault secret show --vault-name chaseTestVault --name secret2 --query value) >> $GITHUB_ENV
      - name: remap secrets
        shell: bash
        run: |-
          echo ENV_SECRET=${{ steps.az-cli-testing.outputs.secret1 }} >> $GITHUB_ENV
      - name: check secret outputs and env
        run: |-
          echo ${{ steps.az-cli-testing.outputs.secret1 }}
          echo ${{ steps.az-cli-testing.outputs.secret2 }}
          echo ${{ env.ENV_SECRET }}
          echo $ENV_SECRET

