name: Output Test

on:
  push:
    branches: [main]

jobs:
  output-testing:
    runs-on: ubuntu-latest
    steps:
      - run: |-
          echo "fooSecret=$(curl 'http://www.randomnumberapi.com/api/v1.0/random')" >> $GITHUB_OUTPUT
          echo "barSecret=$(curl 'http://www.randomnumberapi.com/api/v1.0/random')" >> $GITHUB_OUTPUT
        id: step1
      - run: |-
          echo ${{ steps.step1.outputs.fooSecret }}
          echo ${{ steps.step1.outputs.barSecret }}
  az-cli-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - id: az-cli-testing
        uses: azure/cli@v1.0.7
        with:
          inlineScript: |-
            echo 'Name1=$(az keyvault secret show --vault-name chaseTestVault --name secret1 --query value)' >> $GITHUB_OUTPUT
            echo 'Name2=$(az keyvault secret show --vault-name chaseTestVault --name secret2 --query value)' >> $GITHUB_OUTPUT
      - name: set job envs
        shell: bash
        run: echo 'ENV_SECRET=${{ steps.az-cli-testing.outputs.Name2 }}' >> $GITHUB_ENV
      - run: |-
          echo ${{ steps.az-cli-testing.outputs.Name1 }}
          echo ${{ steps.az-cli-testing.outputs.Name2 }}
          echo ${{ env.ENV_SECRET }}
