name: Output Test

on:
  push:
    branches: [main]

jobs:
  output-testing:
    runs-on: ubuntu-latest
    steps:
      - run: |-
          echo "fooSecret=$(curl 'http://www.randomnumberapi.com/api/v1.0/random')" >> $GITHUB_OUTPUT
          echo "barSecret=$(curl 'http://www.randomnumberapi.com/api/v1.0/random')" >> $GITHUB_OUTPUT
        id: step1
      - run: |-
          echo ${{ steps.step1.outputs.fooSecret }}
          echo ${{ steps.step1.outputs.barSecret }}
  az-cli-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - id: az-cli-testing
        uses: azure/cli@v1.0.7
        with:
          inlineScript: |
            echo "foo"
            echo $(az keyvault secret show --vault-name chaseTestVault --name secret1)
      - run: |-
          echo "foo"
      # echo ${{ env.ENV_SECRET }}
      # echo ${{ steps.az-cli-testing.outputs.secret1 }}
      # - name: check secret outputs and env
      #   shell: bash
      #   run: |-
      #     if [ ${{ steps.az-cli-testing.outputs.Name1 }} == 'foo' ]; then
      #       echo "Secret1 (output) is equal to foo"
      #     fi
      #     if  [ ${{ env.ENV_SECRET }} == 'bar' ]; then
      #       echo "Secret2 (env) is equal to bar"
      #     fi

