name: Output Test

on:
  push:
    branches: [main]

jobs:
  output-testing:
    runs-on: ubuntu-latest
    steps:
      - run: |-
          exit 1
      - run: |-
          echo "I shouldn't run"
      - run: |-
          echo "I should always run"
        id: previous  
        if: always()
      - run: |-
          echo "I should run"
        if: ${{ always() && steps.previous.conclusion == 'success' }}


