name: Output Test

on:
  push:
    branches: [main]

jobs:
  output-testing:
    runs-on: ubuntu-latest
    steps:
      - run: |-
          echo "fooSecret=$(curl 'http://www.randomnumberapi.com/api/v1.0/random')" >> $GITHUB_OUTPUT
          echo "barSecret=$(curl 'http://www.randomnumberapi.com/api/v1.0/random')" >> $GITHUB_OUTPUT
        id: step1
      - run: |-
          echo ${{ steps.step1.outputs.fooSecret }}
          echo ${{ steps.step1.outputs.barSecret }}
  az-cli-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - id: az-cli-testing
        run: |-
          secret1=$(az keyvault secret show --vault-name chaseTestVault --name secret1 --query value)
          echo "::add-mask::$secret1"
          echo "secret1=$secret1" >> $GITHUB_ENV

          secret2=$(az keyvault secret show --vault-name chaseTestVault --name secret2 --query value)
          echo "::add-mask::$secret2"
          echo "secret2=$secret2" >> $GITHUB_ENV
      - name: check secret outputs and env
        run: |-
          echo ${{ env.secret1 }}
          echo ${{ env.secret2 }}
          echo $secret1
          echo $secret2

