on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
        with:
          repository: chaseshak/composite-action-example
      - id: root
        uses: chaseshak/composite-action-example@v2
        with:
          who-to-greet: 'Mona the Octocat'
      - id: nested
        uses: chaseshak/composite-action-example/.github/actions@main
        with:
          who-to-greet: 'Mona the Octocat'
      - id: nested_other
        uses: chaseshak/composite-action-example/.github/actions@main
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.root.outputs.random-number }}
        shell: bash
