on: [push]

jobs:
  azure_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: azure/login@v1.4.6
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
      - uses: azure/webapps-deploy@v2.2.10
        with:
          app-name: my-site
          package: my-package.zip
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
        with:
          repository: chaseshak/composite-action-example
      - id: root
        uses: chaseshak/composite-action-example@v2
        with:
          who-to-greet: 'Mona the Octocat'
      - id: nested
        uses: chaseshak/composite-action-example/.github/actions@main
        with:
          who-to-greet: 'Mona the Octocat'
      - id: trailing_slash
        uses: chaseshak/composite-action-example/.github/actions/@main
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.root.outputs.random-number }}
        shell: bash
  reuse:
    uses: chaseshak/composite-action-example/custom/workflow.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      envPAT: "ABC"
